#pragma once

#include "aes_gcm.h"
#include "audio_format.h"

#define SEGMENT_FORMAT_MAGIC              "NCT2"
#define SEGMENT_FORMAT_VERSION            1
#define SEGMENT_FORMAT_HEADER_BYTES       8
#define SEGMENT_FORMAT_FRAMES_PER_CHUNK   50
#define SEGMENT_FORMAT_FRAME_LENGTH_BYTES 2

#define SEGMENT_FORMAT_MAX_CHUNK_PLAINTEXT_BYTES \
    (SEGMENT_FORMAT_FRAMES_PER_CHUNK * (SEGMENT_FORMAT_FRAME_LENGTH_BYTES + AUDIO_FORMAT_MAX_PACKET_BYTES))
#define SEGMENT_FORMAT_MAX_CHUNK_RECORD_BYTES \
    (SEGMENT_FORMAT_MAX_CHUNK_PLAINTEXT_BYTES + AES_GCM_RECORD_OVERHEAD_BYTES)
