#pragma once

#define AUDIO_FORMAT_SAMPLE_RATE_HZ   16000
#define AUDIO_FORMAT_FRAME_MS         20
#define AUDIO_FORMAT_FRAME_SAMPLES    (AUDIO_FORMAT_SAMPLE_RATE_HZ * AUDIO_FORMAT_FRAME_MS / 1000)
#define AUDIO_FORMAT_MAX_PACKET_BYTES 256
